apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: allow-baseline
spec:
  steps:
    - name: non-root-limited-pod-is-accepted
      try:
        - apply:
            file: ../../examples/allowed/non-root-limited-pod.yaml
