apiVersion: v1
kind: Pod
metadata:
  name: denied-missing-limits
  labels:
    app.kubernetes.io/name: denied-missing-limits
    app.kubernetes.io/part-of: gitops-supply-chain-security
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: main
      image: busybox:1.36.1
      command:
        - sh
        - -c
        - "echo denied"
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
