apiVersion: v1
kind: Pod
metadata:
  name: denied-unsigned-flask-api
  labels:
    app.kubernetes.io/name: denied-unsigned-flask-api
    app.kubernetes.io/part-of: gitops-supply-chain-security
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: flask-api
      image: ghcr.io/anouarmohamed/flask-api:unsigned-demo
      command:
        - sh
        - -c
        - "echo denied"
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
